export const GET_MOVIES = 'GET_MOVIES';
export const LOGIN_IN = 'LOG_IN';
export const LOGIN_NOT_AUTHENTICATED = 'LOGIN_NOT_AUTHENTICATED'
export const LOGIN_OUT = 'LOG_OUT';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CLEAN_MESSAGE = 'CLEAN_MESSAGE';

export const CHECKING = 'CHECKING';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const AUTHENTICATED = 'AUTHENTICATED';